Add export CMake Config version file
arximboldi/immer pull request #250
Opened 2023-01-12 03:19 UTC by LilyWangLL

Add export CMake Config version file to fix the use of `find_package(immer VERSION 0.8.0)`.

2023-01-12 06:27 UTC, dg0yt requested changes

2023-01-12 06:27 UTC, dg0yt commented on CMakeLists.txt
> +  ${CMAKE_CURRENT_BINARY_DIR}/ImmerConfigVersion.cmake
Missing quotes.

2023-01-12 10:17 UTC, arximboldi approved these changes
LGTM!

Will merge after CI runs.

2023-01-13 02:10 UTC, LilyWangLL commented
/azp run

2023-01-13 09:00 UTC, merged

2023-04-05 07:47 UTC, tocic commented
This addresses one of the problems mentioned in #57.